#!/usr/bin/env python3
import argparse
import beagle
import os
import sys

def main():
    parser = argparse.ArgumentParser(description='Beagle')
    parser.add_argument('--interface', type=str, required=True, help='The interface to sniff.')
    parser.add_argument('--srcip', type=str, default=r'.', required=False, help='A source internet protocol address to filter on.')
    parser.add_argument('--dstport', type=str, default=r'.', required=False, help='A destination port to filter on.')
    parser.add_argument('-v', '--verbose',  action='store_true', help='Increases message verbosity.')
    args=parser.parse_args()
    return beagle.hunt(args)

if __name__ == '__main__':
    if os.geteuid():
        sys.exit(beagle.color.error('Only root can hunt for packets.'))
    sys.exit(main())
